
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../pages/Navbar"
import Footer from "../pages/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SVECW Website",
  description: "Generated by Nikitha Metta",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
